version: '3'

services:
  server:
    build: server
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    networks:
      net:
        ipv4_address: 172.28.0.2
      outside:

  client1:
    build: client
    cap_add:
      - NET_ADMIN
    networks:
      net:
        ipv4_address: 172.28.1.1

  client2:
    build: client
    cap_add:
      - NET_ADMIN
    networks:
      net:
        ipv4_address: 172.28.2.1

  client3:
    build: client
    cap_add:
      - NET_ADMIN
    networks:
      net:
        ipv4_address: 172.28.3.1

  client4:
    build: client
    cap_add:
      - NET_ADMIN
    networks:
      net:
        ipv4_address: 172.28.4.1

networks:
  net:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  outside:
